blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [    
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail')
]

portfolio_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls'))
    
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=250)
    date = models.DateField()

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Project

def all_blogs(request):
    projects = Project.objects.order_by('-date')
    return render(request, 'blog/all_blogs.html', {'blogs': projects})

def detail(request, blog_id):
    blog = get_object_or_404(Project, pk = blog_id)
    return render(request, 'blog/detail.html',{'blog': blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html' %}

{% block content %}

<div class="container">
    <div class="row">      
        {% for project1 in blogs %}
        
            <a href="{% url 'blog:detail' blog_id=project1.id %}"><h2>{{ project1.title }}</h2></a>
            <h5>{{ project1.date}}</h5>
            <p>{{ project1.description|truncatechars:100 }}</p>
                
        {% endfor %}
    </div>
</div>
{% endblock %}  

blog/templates/blog/detail.html
{% extends 'portfolio/base.html' %}

{% block content %}

{{ blog.title }}
{{ blog.date }}
{{ blog.description|safe }}

{% endblock %}  

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Обязательные метатеги -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Портфолио</title>
  </head>
  <body>    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="https://rinat20.pythonanywhere.com">На главную</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="http://t.me/RinatShamsutdini">Кнопка для связи</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://stepik.org/users/549368941/profile">Профиль на Степике</a>
          </li>
        </ul>
      </div>
    </nav>
      
    {% block content %}{% endblock %}
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://unpkg.com/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://unpkg.com/bootstrap@5.1.0/dist/js/bootstrap.min.js"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% block content %}
<div class="container px-4 text-center" >
    
    <h1>Личное портфолио</h1>

    <a href="{% url 'blog:all_blogs'  %}">Мой блог</a>
    {% load static%}
    <br>
    <a href="{% static 'portfolio/Resume2.pdf' %}">Резюме</a>
    <br>
    <img src="{% static 'portfolio/Rinat.png'%}" class="mx-auto" style="width: 150px;">

    
    <div class="container">
        <div class="row">
            
                {% for project in projects %}
                <div class="col">
                    <h2>{{ project.title }}</h2>
                    <p>{{ project.description }}</p>
                    <img src="{{ project.image.url }}" class="mx-auto" style="width: 300px;" alt="">

                    {% if project.url %}
                    <br><a href="{{ project.url }}">Пройти к курсу</a>        
                    {% endif %}
                </div>
                {% endfor %}
            
        </div>
    </div>

    

</div>
{% endblock %}  